version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tuananh_1098
    ports:
      - 1435:1433
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sql_network

networks: 
  sql_network:
    driver: bridge

volumes:
  sql_data:
  