spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-OCSHGB8:1435;instanceName=SQL2022DEV;databaseName=restaurant_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: Tuananh_1098
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.SQLServerDialect
