spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-OCSHGB8:1435;databaseName=restaurant_db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Tuananh_1098
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database: sql_server
    hibernate:
      ddl-auto: update  # hoặc none tùy nhu cầu
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  logging:
    level:
      org.springframework.security: DEBUG